kill manual test

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -77,37 +77,37 @@ jobs:
       run: cat /tmp/gcc-scratch/g++.log
 
 
-  test-gcc-full:
-    needs: build-gcc
-    runs-on: ubuntu-latest
-    environment: manual
-    steps:
-    - uses: actions/checkout@v6
-    - name: install apt packages
-      run: sudo apt update && sudo apt install g++-14 bzip2 flex build-essential python3 python3-pytest tcl dejagnu expect
-    - uses: webfactory/ssh-agent@v0.10.0
-      with:
-        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-    - name: restore gcc install
-      uses: actions/cache/restore@v5
-      id: cache-gcc
-      with:
-        path: /opt/GCC
-        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
-        fail-on-cache-miss: true
-    - name: fetch gcc submodule
-      run: git submodule update --init --depth=1 -- submodules/gcc
-    - name: run tests
-      run: |
-        mkdir -p /tmp/gcc-scratch
-        SRCDIR="$(realpath submodules/gcc)"
-        cd /tmp/gcc-scratch
-        "$SRCDIR/contrib/test_installed" --prefix=/opt/GCC --without-{gfortran,objc,gcc} --with-auto-host-h="$(find /opt/GCC -name auto-host.h)" -- --all
-    - name: dump log on failure
-      if: ${{ failure() }}
-      run: cat /tmp/gcc-scratch/g++.log && exit 1
-    - name: dump log on success
-      run: cat /tmp/gcc-scratch/g++.log
+  # test-gcc-full:
+  #   needs: build-gcc
+  #   runs-on: ubuntu-latest
+  #   environment: manual
+  #   steps:
+  #   - uses: actions/checkout@v6
+  #   - name: install apt packages
+  #     run: sudo apt update && sudo apt install g++-14 bzip2 flex build-essential python3 python3-pytest tcl dejagnu expect
+  #   - uses: webfactory/ssh-agent@v0.10.0
+  #     with:
+  #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+  #   - name: restore gcc install
+  #     uses: actions/cache/restore@v5
+  #     id: cache-gcc
+  #     with:
+  #       path: /opt/GCC
+  #       key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
+  #       fail-on-cache-miss: true
+  #   - name: fetch gcc submodule
+  #     run: git submodule update --init --depth=1 -- submodules/gcc
+  #   - name: run tests
+  #     run: |
+  #       mkdir -p /tmp/gcc-scratch
+  #       SRCDIR="$(realpath submodules/gcc)"
+  #       cd /tmp/gcc-scratch
+  #       "$SRCDIR/contrib/test_installed" --prefix=/opt/GCC --without-{gfortran,objc,gcc} --with-auto-host-h="$(find /opt/GCC -name auto-host.h)" -- --all
+  #   - name: dump log on failure
+  #     if: ${{ failure() }}
+  #     run: cat /tmp/gcc-scratch/g++.log && exit 1
+  #   - name: dump log on success
+  #     run: cat /tmp/gcc-scratch/g++.log
 
 
   test-libstdcxx-ivl:
